
# ---
## ADD VARIABLES MISSING IN CLEAN LIST

# 2018


CLEAN.SURVEY.2018 <- CLEAN.SURVEY.2018 %>% 
  mutate(
    JOB.PAY = NA,
    JOB.DESCRIPTION = NA,
    FREELANCE.OR.CONSULTANT = NA,
    JOB.DATAVIS.LACKSKILLS = NA,
    JOB.DATAVIS.LEADERSHIP.UNDERSTANDING = NA,
    JOB.DATAVIS.REACH = NA,
    LGBTQ = NA,
    SPOKEN.LANGUAGE = NA
  )

CLEAN.SURVEY.2018$YEAR <- "2018"

SECOND <- CLEAN.SURVEY.2018 %>% 
  select(
    YEAR,
    COMMUNITY.EXPECTATION,
    COMMUNITY.LEADERS,
    COUNTRY,
    DATAVIS.EDU,
    DATAVIS.EDU.METHOD,
    DATAVIS.TIME,
    EDU.BACKGROUND,
    EDU.MAJOR,
    EXPERIENCE.DATAVIS.YEARS,
    FREELANCE.OR.CONSULTANT,
    GENDER,
    JOB.DATASCI.HOURS,
    JOB.DATAVIS.ASPIRATION,
    JOB.DATAVIS.AUDIENCE,
    JOB.DATAVIS.AUDIENCEDATAVISCONSUMPTION,
    JOB.DATAVIS.AUDIENCEDATAVISUSE,
    JOB.DATAVIS.AUDIENCEKNOWLEGE,
    JOB.DATAVIS.AUDIENCERELATIONSHIP,
    JOB.DATAVIS.CHANGE,
    JOB.DATAVIS.CHARTSUSED,
    JOB.DATAVIS.EXPECTATIONS,
    JOB.DATAVIS.FATIGUE,
    JOB.DATAVIS.FOCUS,
    JOB.DATAVIS.FRUSTRATION,
    JOB.DATAVIS.GOALS,
    JOB.DATAVIS.HOURS,
    JOB.DATAVIS.INTENT,
    JOB.DATAVIS.LACKSKILLS,
    JOB.DATAVIS.LEADERSHIP,
    JOB.DATAVIS.LEADERSHIP.UNDERSTANDING,
    JOB.DATAVIS.NEWTOOLS,
    JOB.DATAVIS.ORGANIZATION,
    JOB.DATAVIS.PERSONALKNOWLEDGE,
    JOB.DATAVIS.PRESENTATION,
    JOB.DATAVIS.REACH,
    JOB.DATAVIS.RESOURCES,
    JOB.DATAVIS.TOOLCHOICE,
    JOB.DATAVIS.TOOLS,
    JOB.DATAVIS.USE,
    JOB.DESCRIPTION,
    JOB.DESIGN.HOURS,
    JOB.ENGINEERING.HOURS,
    JOB.IMPROVEMENT,
    JOB.PAY,
    JOB.PORTFOLIO.HOURS,
    JOB.PREPWORK.HOURS,
    JOB.SECTOR,
    LGBTQ,
    SPOKEN.LANGUAGE
  )

rm(CLEAN.SURVEY.2018, survey.2018)
