
CLEAN.SURVEY.2017 <- survey.2017

colnames(CLEAN.SURVEY.2017) <- c("TIMESTAMP", "EXPERIENCE.YEARS", "EDU.BACKGROUND", 
                           "DATAVIS.EDU", "DATAVIS.INTENT", "DATAVIS.ENTRYJOB", 
                           "JOB.TITLE", "JOB.PAY", "JOB.DATAVIS.FOCUS", "JOB.DATAVIS.INTENT",
                           "JOB.STATUS", "JOB.DATAVIS.USE", "JOB.DATAVIS.ORGANIZATION", "JOB.DATAVIS.USE",
                           "JOB.DATAVIS.LEADERSHIP", "JOB.DATAVIS.POSITION", "JOB.DATAVIS.PERCENTAGE",
                           "JOB.ENGINEERING.PERCENTAGE", "JOB.DATASCI.PERCENTAGE", "JOB.DESIGN.PERCENTAGE",
                           "JOB.PREPWORK.PERCENTAGE", "JOB.DATAVIS.TOOLS", "JOB.DATAVIS.TOOLCHOICE",
                           "JOB.DATAVIS.PRESENTATION", "JOB.DATAVIS.CHARTSUSED",
                           "JOB.DATAVIS.AUDIENCE", "JOB.DATAVIS.AUDIENCEKNOWLEGE",
                           "JOB.DATAVIS.AUDIENCEDATAVISCONSUMPTION",
                           "JOB.DATAVIS.AUDIENCEDATAVISUSE", "JOB.DATAVIS.AUDIENCERELATIONSHIP",
                           "JOB.FRUSTRATION", "JOB.DATAVIS.FRUSTRATION", 
                           "JOB.DATAVIS.CHANGE", "JOB.DATAVIS.PERSONALKNOWLEDGE",
                           "JOB.IMPROVEMENT", "COMMUNITY.EXPECTATION", 
                           "cOMMUNITY.LEADERS", "DATAVIS.TIME", "GENDER", "AGE",
                           "REGION", "ETHNICITY", "JOB.SECTOR")
